```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
```

---
Policy Rules Database Update Schedule
---

```{r table}
UpdateSchedule <- data.frame( Program = c("Federal Poverty Guidelines (FPL)",
                                          "Affordable Care Act",
                                          "Supplemental Nutrition Assistance Program (SNAP)",
                                          "Federal Taxes and Credits",
                                          "State Taxes and Tax Credits",
                                          "National School Lunch and School Breakfast Programs",
                                          "Early Head Start and Head Start",
                                          "Temporary Assistance for Needy Families (TANF)",
                                          "Childcare Development Fund Subsidies (CCDF)",
                                          "Special Supplemental Nutrition Program for Women, Infants, and Children (WIC)",
                                          "Supplemental Security Income",
                                          "Social Security Disability Insurance",
                                          "Housing Costs",
                                          "Medicaid",
                                          "Wage Projections",
                                          "Section 8 Housing Voucher",
                                          "State Median Income",
                                          "National School Lunch and School Breakfast Programs",
                                          "Childcare Development Fund Subsidies (CCDF)",
                                          "Supplemental Nutrition Assistance Program (SNAP)",
                                          "Childcare Development Fund Subsidies (CCDF)",
                                          "Temporary Assistance for Needy Families (TANF)",
                                          "ALICE Expense Data"),
                              Description = c("New data released",
                                              "Updates to subidity eligibility and marketplace average monthly benchmark premiums",
                                              "Adjust eligibility based on new FPL and update Broad Based Catergorical Elgibility (BBCE) rules",
                                              "Update to reflect new tax bracket definitions and credit amounts and eligibility",
                                              "Update to reflect new tax bracket definitions and credit amounts and eligibility",
                                              "Update eligibility thresholds to reflect new FPL release",
                                              "Update eligibility thresholds to reflect new FPL release",
                                              "Update eligibility thresholds to reflect new FPL release",
                                              "Update eligibility thresholds to reflect new FPL release",
                                              "Update eligibility thresholds to reflect new FPL release",
                                              "Update eligibility thresholds to reflect new FPL release",
                                              "Update eligibility thresholds to reflect new FPL release",
                                              "ALICE team updates estimates for housing costs",
                                              "Update rules around income eligibility and premium estimates",
                                              "Update wage growth projections with new BLS data",
                                              "Update HUD Fair Market Rates, income limits, and area median income estimates",
                                              "New data is released",
                                              "Update eligibility thresholds to reflect new SMI release",
                                              "Update eligibility thresholds to reflect new SMI release",
                                              "Update with new SNAP rules, Cost of Living Adjustments, Heat and Eat rules, and Standard Utility Allowences",
                                              "Scan state level sources to see there have been updates to policy rules or copay schedules",
                                              "Scan state level sources to see there have been updates to policy rules or benefit allotments",
                                              "ALICE team updates estimates for costs"), 
                              Date = c("January 2026",
                                       "January 2026",
                                       "January 2026",
                                       "January 2026",
                                       "January 2026",
                                       "January 2026",
                                       "January 2026",
                                       "January 2026",
                                       "January 2026",
                                       "January 2026",
                                       "January 2026",
                                       "January 2026",
                                       "January 2026",
                                       "March/May 2026",
                                       "April/May 2026",
                                       "April 2026",
                                       "July 2026",
                                       "July 2026",
                                       "July 2026",
                                       "October 2026",
                                       "October 2026",
                                       "October 2026",
                                       "November/December 2026") )

kable(UpdateSchedule,booktabs=TRUE)%>%kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```
